title:              Jorge Ortiz Escribano
email:              jorgeortizescr@gmail.com
description:        Blog about programming, embedded systems, FPGA and more!
author:             Jorge Ortiz Escribano
baseurl:            ""
url:                "https://jorgeortiz97.github.io/"

# Social Profiles
# twitter_username:     
github_username:        jorgeortiz97
# facebook_username:    StartBootstrap
linkedin_username:      jorge-ortiz-escribano-72737616b

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
 
collections:
    topics:
        output: true
 